#! /usr/bin/env python3
# Using /home/teuben/LMT/lmtoy/data_lmt/unity/data_lmt.log
# 2018-S1-MU-1 - Science
#   script generated by source_obsnum.sh
import os
import sys

from lmtoy import runs

project="2018-S1-MU-1"

# Dictionary of sources, each with a list of obsnum's in this project
# negative obsnums are ignored in the combinations. See also comments.txt
# for obsnum specific comments and parameters!
on = {}

on["AFGL2088"] = \
 [ 77080, 77081, 77082, 77084, 77085, 77086, 77088, 77089, 77090, 77093, 77094, 77095,]

on["IRAS_17028-1004"] = \
 [ 76794, 76795, 76796, 76798, 76799, 76800, 76802, 76803, 76804, 76807, 76808, 76809,]

on["IRAS_17423-1755"] = \
 [ 76951, 76952, 76953, 76955, 76956, 76957, 76959, 76960, 76961, 76964, 76965, 76966,]

on["PN_Cn3-1"] = \
 [ 77203, 77204, 77205, 77207, 77208, 77209, 77212, 77213, 77214, 77216, 77217, 77218,]

on["PN_M_2-43"] = \
 [ 77443, 77444, 77445, 77447, 77448, 77449,]

# parameters for the first pass of the pipeline (restart=1 is automatically enforced here)
pars1 = {}

pars1["AFGL2088"] = ""
pars1["IRAS_17028-1004"] = ""
pars1["IRAS_17423-1755"] = ""
pars1["PN_Cn3-1"] = ""
pars1["PN_M_2-43"] = ""

# parameters for the (optional) second pass of the pipeline (e.g. for bank=0)
pars2 = {}

pars2["AFGL2088"] = ""
pars2["IRAS_17028-1004"] = ""
pars2["IRAS_17423-1755"] = ""
pars2["PN_Cn3-1"] = ""
pars2["PN_M_2-43"] = ""

# parameters for the (optional) third pass of the pipeline (usually for bank=1)
pars3 = {}

pars3["AFGL2088"] = ""
pars3["IRAS_17028-1004"] = ""
pars3["IRAS_17423-1755"] = ""
pars3["PN_Cn3-1"] = ""
pars3["PN_M_2-43"] = ""

# Found 5 source(s) for 2018-S1-MU-1

if __name__ == "__main__":
    runs.mk_runs(project, on, pars1, pars2, pars3, sys.argv)
